### ISSUE TITLE
New Feature Request:  multi users and alert equal file name?

### ISSUE THREAD

**Issue by oncelot** [jasekz/laradrop#15]
Hi guy,
I will have many assets files managed by laradrop, can laradrop support multi users ?
save the file in dinamic directory?
it's possibile alert if the file have equal name with other file?
thanks

**Comment by jasekz** [comment]
Yes, but Laradrop is meant to be generic and does not make assumptions on how your ACL is implemented, so that is business logic which you will need to implement.  The best way to accomplish this, is by handling the events, FileWasUploaded & FileWasDeleted.  These events pass the file object which you can then associate/disassociate with users.  Another way is to create your own controller and extend the LaradropController to include the additional logic.  The same principle applies to saving in a dynamic directory and custom file validation.  The file validation would be better suited for the controller method, as you probably don't want to proceed if the name already exists.
