### ISSUE TITLE
After installing into an existing project laradrop gives this error on console

### ISSUE THREAD

**Issue by DamPe88** [jasekz/laradrop#16]
I have installed laradrop into a 5.1 laravel ongoing project, but when ever i try to load the dropzone, system gives me this error on browser console.

/laradrop/containers not found.

can you help me on this?.

**Comment by jasekz** [comment]
Thanks for bringing this to my attention.  Would you be able to post a screen shot of the error?

**Comment by DamPe88** [comment]
Sorry i wont be able to post a screen shot.
error message is some thing like this.

http://{host_name}/user/laradrop/containers/ not found

**Comment by jasekz** [comment]
So for some reason, it appears that the url is not routing to the laradrop controller/function.  Can you verify that you added 'Jasekz\Laradrop\LaradropServiceProvider' to your providers array in app.php?  Also, are you running your whole app out of the `user` directory, or is `/user/...` just part of a route or route group for user pages?

**Comment by DamPe88** [comment]
Yes, added that to the app.php into the providers array.

part of a route

**Comment by jasekz** [comment]
Are you defining `laradrop-containers` explicitly?  By default, it should go to `/laradrop/containers`.

```
<div class="laradrop"
    laradrop-containers="{{ route('yourCustomUserRoute.containers') }}"
    laradrop-csrf-token="{{ csrf_token() }}">
</div>
```

**Comment by DamPe88** [comment]
strange thing is ,this works in a fresh laravel copy.will try this and let you know

**Comment by jasekz** [comment]
Well, by default, it will route to `http://{host_name}/laradrop/containers/`, but yours is routing to `http://{host_name}/user/laradrop/containers/`.  Because of that, you'll need to explicitly handle that route -whether by defining it in routes, or providing your own controller to handle the request.  If you could, go to `http://{host_name}/laradrop/containers/` in your browser and you should see a json response.

**Comment by DamPe88** [comment]
Ok.so if i do this 

> <div class="laradrop"
    laradrop-containers="{{ route('yourCustomUserRoute.containers') }}"
    laradrop-csrf-token="{{ csrf_token() }}">

> </div>

this should work?.I will try this and let you know.

Thanks a lot Jasekz

**Comment by jasekz** [comment]
Can you first verify that going directly to `http://{host_name}/laradrop/containers/` in your browser displays a json response?

**Comment by DamPe88** [comment]
Hi Jasekz,
Sory for the late reply.
Yes i do get a json response when i try this one out on browser

http://{host_name}/laradrop/containers/

**Comment by jasekz** [comment]
Try using this:
```
<div class="laradrop"
    laradrop-file-source="{{ route('laradrop.index') }}" 
    laradrop-upload-handler="{{ route('laradrop.store') }}"
    laradrop-file-delete-handler="{{ route('laradrop.destroy', 0) }}"
    laradrop-file-move-handler="{{ route('laradrop.move') }}"
    laradrop-file-create-handler="{{ route('laradrop.create') }}"
    laradrop-containers="{{ route('laradrop.containers') }}"
    laradrop-csrf-token="{{ csrf_token() }}">
</div>
```

**Comment by flexgrip** [comment]
This isn't working for me either. I'll let you know if I find a solution. But basically something is messed up with the route. Instead of point to /laradrop/containers it's using the route as a relative path. So wherever you instantiate the laradrop instance, it puts it on the end of the url. For example I loaded it in a view with a route /clans/step/5 and the resulting route laradrop tries to hit is /clans/step/5/laradrop/containers.

Hitting laradrop/containers directly gives the appropriate json response.

**Comment by flexgrip** [comment]
Just to follow-up, here's what we're seeing: http://d.pr/i/Op2t

**Comment by flexgrip** [comment]
I think I figured it out. After vendor:publish, in public/vendor..../laradrop.js line 11.

Something is up. So no matter what you specify in the laradrop-containers="" attribute, it still uses the default you set on the end of line 11. If you just put a slash in front of that, it fixes everything. So clearly its not reading the attribute.

However, that kind of sucks because I want to bind my own controllers. Which I would need to do using those attributes. Would rather not hack laradrop.js since that can be overwritten by vendor:publish on deploy.

Any thoughts on why that isn't being picked up?

**Comment by flexgrip** [comment]
Sorry for sending so many updates. I think the problem DamPe88 is running into is he's pasting both of the jquery.onload functions you posted. The simple and the custom one.

When you paste both in, you get the problem with the route. If he just removes one, that should fix it.

On another note, how in the hell do I get rid of all this root/folder/container crap? How do I get this version of the dropzone implementation to look like the examples on the dropzonejs site. Just a box that you can either drag files on or click? I want to get rid of the idea of folders or containers and just bind all the images the user uploads to their user_id.

I can do that part on my own, I just don't see a way to get rid of all of the root folder crap.

Any thoughts?

**Comment by jasekz** [comment]
@flexgrip @DamPe88 
I just pushed out a fix for this.  When you get a chance, can you update your laradrop install and try again?  Let me know if the issue persists and thanks for bringing this to my attention.

**Comment by flexgrip** [comment]
Seems to work if you don't override the default values.

Just as a matter of constructive criticism... I realized tonight that I spent more time trying to remove all the styling, containers and functionality from this package than if I would just just hooked up dropzone.js and a made a few endpoints to support index, store and delete.

I'm assuming you built this for a specific project? Considering the model doesn't save the user who uploaded or anything like that, I imagine you probably built this for something specific.

**Comment by jasekz** [comment]
It works if you override the default values as well, but if you route it to a different controller, than it's your responsibility to provide the handler (which could extend the laradrop controller).

To respond to your comment, this is actually a generic solution and only knows about the files and dir structure.  I had people ask me about support for `users` and such, but that would violate the principle of loose coupling and I feel it's better to leave it open for devs to implement - either via event handlers or extending the laradrop controller.  But you're right, this may not be a solution for everyone.
